apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: solar-system
type: Opaque
stringData:
  secret-key-admin-auth-token: "SECRETKEYADMINAUTHTOKENNADMINPASSWORDCREATEDBYIOTTECHSOFTWARE"
  secret-key-admin-password: "SECRETKEYBFOOTLOGINADMINPASSWORDCREATEDBYIOTTECHSOFTWARE"
  mqtt-username: "your_mqtt_username"
  mqtt-password: "your_mqtt_password"