apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: solar-system
data:
  NODE_ENV: "production"
  DB_DIALECT: "mysql"
  DB_NAME: "iot_solar"
  BACKEND_PORT: "5000"
  ROOT_ROUTES: "/api"
  SALT_ROUND: "15"
  MQTT_HOST: "mqtt://everonsolar.com:1883"
  MQTT_TOPIC: "mppt_demo"
  CORS_ORIGIN: "http://147.93.30.6,http://frontend:80"